ALTER TABLE `StreetDict_SS2`

ADD FOREIGN KEY (`StrID`)
REFERENCES `Streets`(`StrID`)
ON UPDATE CASCADE ON DELETE CASCADE,

ADD FOREIGN KEY (`StreetID`)
REFERENCES `StreetDict`(`StreetID`)
ON UPDATE CASCADE ON DELETE CASCADE,

ADD FOREIGN KEY (`CityDistrictID`)
REFERENCES `CityDistricts`(`CityDistrictID`)
ON UPDATE CASCADE ON DELETE CASCADE,

ADD FOREIGN KEY (`CitySubdistrictID`)
REFERENCES `CitySubdistricts`(`CitySubdistrictID`)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `StreetDict_SS2_History`
ADD FOREIGN KEY (`StreetDict_SS_ID`)
REFERENCES `StreetDict_SS2`(`StreetDict_SS_ID`)
ON UPDATE CASCADE ON DELETE CASCADE;