ALTER TABLE `SummarySettlements2`

ADD FOREIGN KEY (`SettlementTypeID`)
REFERENCES `SettlementTypes`(`SettlementTypeID`)
ON UPDATE CASCADE ON DELETE CASCADE,

ADD FOREIGN KEY (`CityID`)
REFERENCES `Cities`(`CityID`)
ON UPDATE CASCADE ON DELETE CASCADE,

ADD FOREIGN KEY (`RegionID`)
REFERENCES `Regions`(`RegionID`)
ON UPDATE CASCADE ON DELETE CASCADE,

ADD FOREIGN KEY (`AreaID`)
REFERENCES `Areas`(`AreaID`)
ON UPDATE CASCADE ON DELETE CASCADE,

ADD FOREIGN KEY (`SuburbID`)
REFERENCES `Suburbs`(`SuburbID`)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `StreetDict_SS2`
ADD FOREIGN KEY (`SummarySettlementID`)
REFERENCES `SummarySettlements2`(`SummarySettlementID`)
ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE `StreetDict_SS2_History`
ADD FOREIGN KEY (`SummarySettlementID`)
REFERENCES `SummarySettlements2`(`SummarySettlementID`)
ON UPDATE CASCADE ON DELETE CASCADE;
